- hosts: all
  connection: local
  gather_facts: false
  order: sorted
  vars:
    #ansible_python_interpreter: "/usr/local/bin/python"
    infoblox_provider:
      host: "10.10.96.86"
      username: "admin"
      password: "Techno123!"
    vcenter_username: "cdbass"
    vcenter_password: "N35b32IM"
    vcenter_hostname: "vc-irv.techlab.com"




  tasks:
    - name: Remove Node
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        name: "{{ inventory_hostname }}"
        force: yes
        state: absent
      delegate_to: localhost
      register: facts
      run_once: true

    - name: Simple A record (IPV4 address) lookup for "{{ inventory_hostname }}"
      debug: msg="{{ lookup('dig', "{{ inventory_hostname }}")}}"
      register: ns

    - name: remove Public IP A Records for host
      nios_a_record:
        name: "{{ inventory_hostname }}.techlab.com"
        ipv4: "{{ ns.msg }}"
        state: absent
        provider: "{{ infoblox_provider }}"
      connection: local
      run_once: true

